In [ ]:
str = "PYnative"
size = len(list(str))
for i in range(0, size -1, 2):
  print(str[i])



P
n
t
v


In [ ]:
str = "PYnative"
size = list(str)
for i in size[0::2]:
  print(i)

P
n
t
v


In [ ]:
def remove_chars(word, n):
    # write your code
    x = word[n:]
    return x
print("Removing characters from a string")
print(remove_chars("pynative", 4))
# output 'tive' first four characters are removed

print(remove_chars("pynative", 2))

Removing characters from a string
tive
native


In [ ]:
def check_list_num(n):
  fn = n[0]
  fl = n[-1]

  if fn == fl:
    return True
  else:
    return False
x = [10, 20, 30, 40, 10]
print(check_list_num(x))


True


In [ ]:
t = [10, 20, 33, 46, 55]
for i in t:
  if i % 5 == 0:
    print(i)

10
20
55


In [ ]:
x = "Emma is good developer. Emma is a writer"
c = x.count("Emma")
print(c)

2


In [ ]:
for i in range(5):
  for j in range(i):
    print(i, end=" ")
  print("\t")

	
1 	
2 2 	
3 3 3 	
4 4 4 4 	


In [ ]:
n = 3456
while n > 0:
  d = n % 10
  n = n // 10
  print(d, end = " ")

6 5 4 3 

In [ ]:
for i in range(1,10):
  for j in range(1,10):
    print(i * j, end = " ")
  print("\t\t")

1 2 3 4 5 6 7 8 9 		
2 4 6 8 10 12 14 16 18 		
3 6 9 12 15 18 21 24 27 		
4 8 12 16 20 24 28 32 36 		
5 10 15 20 25 30 35 40 45 		
6 12 18 24 30 36 42 48 54 		
7 14 21 28 35 42 49 56 63 		
8 16 24 32 40 48 56 64 72 		
9 18 27 36 45 54 63 72 81 		


In [ ]:
for i in range(6,0,-1):
  for j in range(0, i-1):
    print("*", end = " ")
  print(" ")


* * * * *  
* * * *  
* * *  
* *  
*  
 


In [ ]:
def merge_list(list1, list2):
  list3 = []

  for i in list1:
    if i % 2 != 0:
      list3.append(i)

  for i in list2:
    if i % 2 == 0:
      list3.append(i)

  return list3

list1 = [10, 20, 25, 30, 35]
list2 = [40, 45, 60, 75, 90]
merge_list(list1, list2 )

[25, 35, 40, 60, 90]

In [ ]:
n =6578
while n > 0:
  d = n % 10
  n = n // 10
  print(d, end=" ")

8 7 5 6 

In [ ]:
def no_duplicate(str1):
  letter = {}
  for i in str1:
    if i in letter:
      return False
    letter[i] = True
  return True

if __name__ == "__main__":
  import sys
  print(no_duplicate(sys.argv[-1]))
  print(no_duplicate("adadsbsd"))





False
False


In [ ]:
def largest_num(nums):
  max_num = nums[0]
  for num in nums:
    if num > max_num:
      max_num = num
  return max_num

my_nums = [0,15,68,1,0,-55]
max_num = largest_num(my_nums)


print(max_num)

68


In [ ]:
class CompressString(object):

    def compress(self, string):
        if string is None or not string:
            return string
        result = ''
        prev_char = string[0]
        count = 0
        for char in string:
            if char == prev_char:
                count += 1
            else:
                result += self._calc_partial_result(prev_char, count)
                prev_char = char
                count = 1
        result += self._calc_partial_result(prev_char, count)
        return result if len(result) < len(string) else string

    def _calc_partial_result(self, prev_char, count):
        return prev_char + (str(count) if count > 1 else '')


#%%writefile test_compress.py
import unittest


class TestCompress(unittest.TestCase):

    def test_compress(self, func):
        self.assertEqual(func(None), None)
        self.assertEqual(func(''), '')
        self.assertEqual(func('AABBCC'), 'AABBCC')
        self.assertEqual(func('AAABCCDDDDE'), 'A3BC2D4E')
        self.assertEqual(func('BAAACCDDDD'), 'BA3C2D4')
        self.assertEqual(func('AAABAACCDDDD'), 'A3BA2C2D4')
        print('Success: test_compress')


def main():
    test = TestCompress()
    compress_string = CompressString()
    test.test_compress(compress_string.compress)


if __name__ == '__main__':
    main()

Success: test_compress


In [ ]:
def is_unique(input_string):
    hash_table = [False]*128  # hash table implemented as 128 bit vector
    for character in input_string:  # inspect each character
        index = ord(character)  # convert character into its ASCII value
        if hash_table[index]:  # check if bit at this ASCII value is True
            return False
        hash_table[index] = True  # add unobserved character to hash table
    return True

if __name__ == "__main()":
  main()
  input_string = "abcde"
  print(is_unique("abcde"))
  print(is_unique(input_string))


In [ ]:
w = input("Word:")
x = list(w)
for i in x[::2]:
  print(i, end=" ")

Word:sdssdsd
s s d d 

In [2]:
import numpy as np
print(np.__version__)
x = np.array([1,2,3,4,5])

print(x)
print(type(x))


2.0.2
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)



[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [4]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])
print(arr[2] + arr[3])


arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[0, -1])

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

2
7
2nd element on 1st row:  2
6
Last element from 2nd dim:  5
[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [22]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)


arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)


arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)


int64
<U6
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32
[1 2 3]
int32
[1 2 3]
int64
[ True False  True]
bool


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)


arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)




[42  2  3  4  5]
[1 2 3 4 5]
[31  2  3  4  5]
[31  2  3  4  5]
None
[1 2 3 4 5]
(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

newarr = arr.reshape(3, 3)

print(newarr)


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)


arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)




[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6]
