DAY - 1

In [2]:
def print_data_types():
    """Prints values of different data types."""
    integer_var = 10
    float_var = 3.14
    string_var = "Hello, world!"
    boolean_var = True

    print("Integer:", integer_var)
    print("Float:", float_var)
    print("String:", string_var)
    print("Boolean:", boolean_var)

def swap_numbers(num1, num2):
    """Swaps two numbers without using a third variable."""
    num1 = num1 + num2
    num2 = num1 - num2
    num1 = num1 - num2
    return num1, num2

def convert_temperature(temperature, unit):
    """Converts temperature between Fahrenheit and Celsius."""
    if unit == "F":
        celsius = (temperature - 32) * 5 / 9
        return celsius
    elif unit == "C":
        fahrenheit = (temperature * 9 / 5) + 32
        return fahrenheit
    else:
        return "Invalid unit"

def calculate_area_perimeter(length, width):
    """Calculates the area and perimeter of a rectangle."""
    area = length * width
    perimeter = 2 * (length + width)
    return area, perimeter

# Example usage
print_data_types()

num1, num2 = swap_numbers(10, 20)
print("Swapped numbers:", num1, num2)

fahrenheit = 86
celsius = convert_temperature(fahrenheit, "F")
print("Celsius:", celsius)

length = 5
width = 3
area, perimeter = calculate_area_perimeter(length, width)
print("Area:", area)
print("Perimeter:", perimeter)

Integer: 10
Float: 3.14
String: Hello, world!
Boolean: True
Swapped numbers: 20 10
Celsius: 30.0
Area: 15
Perimeter: 16


In [ ]:
print("darshan")

In [6]:
l=[10,20,30,True,"darshan",298.877,30,10,20]
print(l)
l.append(2027)
print(l)
l.remove(30)
print(l)

[10, 20, 30, True, 'darshan', 298.877, 30, 10, 20]
[10, 20, 30, True, 'darshan', 298.877, 30, 10, 20, 2027]
[10, 20, True, 'darshan', 298.877, 30, 10, 20, 2027]


In [9]:
t=(10,20,30,40,50,True,76.876,10,20,30)
print(t)
t.count(10)

(10, 20, 30, 40, 50, True, 76.876, 10, 20, 30)


2

In [13]:
s={10,20,30,2027,3045,988,True,.98877,10,20,30}
print(s)


{0.98877, True, 3045, 10, 2027, 20, 988, 30}


In [16]:
d={1:"darshan",2:"rahul",3:"sudeep",4:"darshan"}
print(d)
print(d.keys)

{1: 'darshan', 2: 'rahul', 3: 'sudeep', 4: 'darshan'}
<built-in method keys of dict object at 0x000001A31D549D40>


In [3]:
def is_prime(number):
    """Checks if a number is prime."""
    if number <= 1:
        return False
    for i in range(2, int(number**0.5) + 1):
        if number % i == 0:
            return False
    return True

def factorial_recursive(num):
    """Calculates the factorial of a number using recursion."""
    if num == 0:
        return 1
    else:
        return num * factorial_recursive(num - 1)

def calculate_power(base, exponent):
    """Calculates the power of a number using recursion."""
    if exponent == 0:
        return 1
    else:
        return base * calculate_power(base, exponent - 1)

def is_leap_year(year):
    """Checks if a given year is a leap year."""
    if year % 4 == 0 and (year % 100 != 0 or year % 400 == 0):
        return True
    else:
        return False

# Example usage
number = 17
if is_prime(number):
    print(number, "is a prime number.")
else:
    print(number, "is not a prime number.")

num = 5
factorial = factorial_recursive(num)
print("Factorial of", num, ":", factorial)

base = 2
exponent = 3
power = calculate_power(base, exponent)
print(base, "raised to the power of", exponent, ":", power)

year = 2024
if is_leap_year(year):
    print(year, "is a leap year.")
else:
    print(year, "is not a leap year.")

17 is a prime number.
Factorial of 5 : 120
2 raised to the power of 3 : 8
2024 is a leap year.


In [4]:
def print_fibonacci(terms):
    """Prints the Fibonacci series up to a given term."""
    first_term = 0
    second_term = 1
    print(first_term, second_term, end=" ")
    for i in range(2, terms):
        next_term = first_term + second_term
        print(next_term, end=" ")
        first_term, second_term = second_term, next_term

def find_largest_element(array):
    """Finds the largest element in an array."""
    largest = array[0]
    for num in array:
        if num > largest:
            largest = num
    return largest

def bubble_sort(array):
    """Sorts an array in ascending order using bubble sort."""
    n = len(array)
    for i in range(n):
        for j in range(0, n - i - 1):
            if array[j] > array[j + 1]:
                array[j], array[j + 1] = array[j + 1], array[j]

def simple_calculator():
    """Implements a simple calculator with basic arithmetic operations."""
    while True:
        num1 = float(input("Enter the first number: "))
        operator = input("Enter the operator (+, -, *, /): ")
        num2 = float(input("Enter the second number: "))

        if operator == "+":
            result = num1 + num2
        elif operator == "-":
            result = num1 - num2
        elif operator == "*":
            result = num1 * num2
        elif operator == "/":
            if num2 == 0:
                print("Error: Cannot divide by zero.")
            else:
                result = num1 / num2
        else:
            print("Invalid operator.")

        print("Result:", result)

        choice = input("Do you want to continue? (y/n): ")
        if choice.lower() != "y":
            break

# Example usage
print_fibonacci(10)
array = [5, 2, 8, 1, 9]
largest = find_largest_element(array)
print("Largest element:", largest)
bubble_sort(array)
print("Sorted array:", array)
simple_calculator()

0 1 1 2 3 5 8 13 21 34 Largest element: 9
Sorted array: [1, 2, 5, 8, 9]


In [20]:
print(6&7)
print(6|7)
print(5&10)
print(5|10)
print(10^7)

print(~10)
print(~-110)
print(~1000)

print(8<<3)
print(8>>3)
print(10>>1)
print(8>>2)
print(8>>3)
print(8>>1)
print(100>>1)
print(100<<1)

6
7
0
15
13
-11
109
-1001
64
1
5
2
1
4
50
200


In [24]:
fruits=["apple","mango","orange","banana"]
print("banana" in fruits)
print("pppp" in fruits)
print("pppp"  not in fruits)
print("apple"  not in fruits)

True
False
True
False


In [1]:
def factorial(num):
    """Calculates the factorial of a number."""
    if num == 0:
        return 1
    else:
        return num * factorial(num - 1)

def is_palindrome(string):
    """Checks if a string is a palindrome."""
    return string == string[::-1]

def calculate_circle_area(radius):
    """Calculates the area of a circle."""
    return 3.14159 * radius * radius

def gcd(a, b):
    """Finds the greatest common divisor (GCD) of two numbers."""
    while b != 0:
        a, b = b, a % b
    return a

# Example usage
num = 5
factorial = factorial(num)
print("Factorial of", num, ":", factorial)

string = "racecar"
if is_palindrome(string):
    print(string, "is a palindrome.")
else:
    print(string, "is not a palindrome.")

radius = 5
area = calculate_circle_area(radius)
print("Area of circle:", area)

a = 12
b = 18
gcd_value = gcd(a, b)
print("GCD of", a, "and", b, ":", gcd_value)

Factorial of 5 : 120
racecar is a palindrome.
Area of circle: 78.53975
GCD of 12 and 18 : 6


In [34]:
a=[10,20,30,40]
b=[10,20,30,40,90]
print(a is  b)
print(b is a)
b=[10,20,30,40,90]
d=[10,20,30,40,90]
c=b
print(b is c)
print(d is not  c)

False
False
True
True


In [49]:
#  list  methods
l=[1,2,3,4,5,True,90.87,"darshan",1,1,1,1]
print(l)
print(type(l))
l.append("engioneer")
print(l)
l.insert(1,"darshabn")
print(l)
l.remove(1)
print(l)
l.remove("darshan")
print(l)
print(l.count("darshan"))
l.reverse()
print(l)
print("hello  darshan  good  morning")

print(l)
print(l)

[1, 2, 3, 4, 5, True, 90.87, 'darshan', 1, 1, 1, 1]
<class 'list'>
[1, 2, 3, 4, 5, True, 90.87, 'darshan', 1, 1, 1, 1, 'engioneer']
[1, 'darshabn', 2, 3, 4, 5, True, 90.87, 'darshan', 1, 1, 1, 1, 'engioneer']
['darshabn', 2, 3, 4, 5, True, 90.87, 'darshan', 1, 1, 1, 1, 'engioneer']
['darshabn', 2, 3, 4, 5, True, 90.87, 1, 1, 1, 1, 'engioneer']
0
['engioneer', 1, 1, 1, 1, 90.87, True, 5, 4, 3, 2, 'darshabn']
hello  darshan  good  morning
['engioneer', 1, 1, 1, 1, 90.87, True, 5, 4, 3, 2, 'darshabn']


In [66]:
l=[1,2,3,4,5,True,90.87,"darshan",1,1,1,1,"cse","cse",2,2,2,2]
print(l)
l.pop()
print(l)
l.remove("cse")
l.insert(6,"engineer")
print(l)
print(l.count(1))
l.reverse()
print(l)

[1, 2, 3, 4, 5, True, 90.87, 'darshan', 1, 1, 1, 1, 'cse', 'cse', 2, 2, 2, 2]
[1, 2, 3, 4, 5, True, 90.87, 'darshan', 1, 1, 1, 1, 'cse', 'cse', 2, 2, 2]
[1, 2, 3, 4, 5, True, 'engineer', 90.87, 'darshan', 1, 1, 1, 1, 'cse', 2, 2, 2]
6
[2, 2, 2, 'cse', 1, 1, 1, 1, 'darshan', 90.87, 'engineer', True, 5, 4, 3, 2, 1]
4


In [70]:
t=(1,2,3,34,4,5,6,67,"darshan","bro","irfan","irfan","darshan")
print(t)
print(t.count("darshan"))

(1, 2, 3, 34, 4, 5, 6, 67, 'darshan', 'bro', 'irfan', 'irfan', 'darshan')
2


In [2]:
def reverse_list(lst):
    """Reverses a list without using the reverse() method."""
    start = 0
    end = len(lst) - 1
    while start < end:
        lst[start], lst[end] = lst[end], lst[start]
        start += 1
        end -= 1

def find_second_largest(lst):
    """Finds the second largest element in a list."""
    if len(lst) < 2:
        return None
    largest = lst[0]
    second_largest = lst[0]
    for num in lst:
        if num > largest:
            second_largest = largest
            largest = num
        elif num > second_largest and num != largest:
            second_largest = num
    return second_largest

def merge_sorted_lists(list1, list2):
    """Merges two sorted lists into a single sorted list."""
    merged_list = []
    i = 0
    j = 0
    while i < len(list1) and j < len(list2):
        if list1[i] < list2[j]:
            merged_list.append(list1[i])
            i += 1
        else:
            merged_list.append(list2[j])
            j += 1
    merged_list += list1[i:]
    merged_list += list2[j:]
    return merged_list

def demonstrate_immutability():
    """Demonstrates the immutability of tuples."""
    tuple_example = (1, 2, 3)
    try:
        tuple_example[0] = 10
    except TypeError as e:
        print("Error:", e)

# Example usage
my_list = [5, 2, 8, 1, 9]
reverse_list(my_list)
print("Reversed list:", my_list)

second_largest = find_second_largest(my_list)
print("Second largest element:", second_largest)

list1 = [1, 3, 5]
list2 = [2, 4, 6]
merged_list = merge_sorted_lists(list1, list2)
print("Merged list:", merged_list)

demonstrate_immutability()

Reversed list: [9, 1, 8, 2, 5]
Second largest element: 9
Merged list: [1, 2, 3, 4, 5, 6]
Error: 'tuple' object does not support item assignment


In [3]:
def count_word_frequency(text):
    """Counts the word frequency in a given text."""
    word_count = {}
    words = text.split()
    for word in words:
        word_count[word] = word_count.get(word, 0) + 1
    return word_count

def implement_phonebook():
    """Implements a simple phonebook using a dictionary."""
    phonebook = {}
    while True:
        choice = input("Enter your choice:\n1. Add contact\n2. Find contact\n3. Exit\n")
        if choice == "1":
            name = input("Enter name: ")
            phone_number = input("Enter phone number: ")
            phonebook[name] = phone_number
            print("Contact added successfully.")
        elif choice == "2":
            name = input("Enter name to find: ")
            if name in phonebook:
                print("Phone number:", phonebook[name])
            else:
                print("Contact not found.")
        elif choice == "3":
            print("Exiting...")
            break
        else:
            print("Invalid choice.")

def find_most_frequent_character(string):
    """Finds the most frequent character in a string."""
    char_count = {}
    for char in string:
        char_count[char] = char_count.get(char, 0) + 1
    most_frequent_char = max(char_count, key=char_count.get)
    return most_frequent_char

def merge_dictionaries(dict1, dict2):
    """Merges two dictionaries."""
    merged_dict = dict1.copy()
    merged_dict.update(dict2)
    return merged_dict

# Example usage
text = "This is a sample text. This is another sentence."
word_count = count_word_frequency(text)
print("Word frequency:", word_count)

implement_phonebook()

string = "hello world"
most_frequent_char = find_most_frequent_character(string)
print("Most frequent character:", most_frequent_char)

dict1 = {"a": 1, "b": 2}
dict2 = {"c": 3, "d": 4}
merged_dict = merge_dictionaries(dict1, dict2)
print("Merged dictionary:", merged_dict)

Word frequency: {'This': 2, 'is': 2, 'a': 1, 'sample': 1, 'text.': 1, 'another': 1, 'sentence.': 1}


In [ ]:
def sum_of_digits(num):
    """Finds the sum of digits of a number."""
    sum = 0
    while num > 0:
        sum += num % 10
        num //= 10
    return sum

def is_pangram(string):
    """Checks if a given string is a pangram."""
    alphabet = set(string.lower())
    return len(alphabet) == 26

def find_prime_factors(num):
    """Finds the prime factors of a number."""
    prime_factors = []
    i = 2
    while i * i <= num:
        while num % i == 0:
            prime_factors.append(i)
            num //= i
        i += 1
    if num > 1:
        prime_factors.append(num)
    return prime_factors

def calculate_square_root(num):
    """Calculates the square root of a number."""
    return num ** 0.5

def adventure_game():
    """Implements a simple text-based adventure game."""
    # Game logic here

def simulate_dice_roll():
    """Simulates a dice roll."""
    import random
    return random.randint(1, 6)

def generate_random_password(length):
    """Generates a random password of a given length."""
    import string
    import random
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

def guessing_game():
    """Implements a simple guessing game."""
    import random
    secret_number = random.randint(1, 100)
    attempts = 0
    while True:
        guess = int(input("Guess a number between 1 and 100: "))
        attempts += 1
        if guess == secret_number:
            print("Congratulations! You guessed the number in", attempts, "attempts.")
            break
        elif guess < secret_number:
            print("Too low. Try again.")
        else:
            print("Too high. Try again.")

def calculate_triangle_area(side1, side2)

In [ ]:
def check_disjoint_sets(set1, set2):
    """Checks if two sets are disjoint."""
    return set1.isdisjoint(set2)

def find_union_intersection(set1, set2):
    """Finds the union and intersection of two sets."""
    union_set = set1.union(set2)
    intersection_set = set1.intersection(set2)
    return union_set, intersection_set

def is_subset(set1, set2):
    """Determines if a set is a subset of another set."""
    return set1.issubset(set2)

def remove_duplicates_using_set(lst):
    """Removes duplicates from a list using a set."""
    unique_set = set(lst)
    return list(unique_set)

# Example usage
set1 = {1, 2, 3}
set2 = {3, 4, 5}
if check_disjoint_sets(set1, set2):
    print("Sets are disjoint.")
else:
    print("Sets are not disjoint.")

union_set, intersection_set = find_union_intersection(set1, set2)
print("Union:", union_set)
print("Intersection:", intersection_set)

if set1.issubset(set2):
    print("Set 1 is a subset of Set 2.")
else:
    print("Set 1 is not a subset of Set 2.")

lst = [1, 2, 3, 2, 4, 1]
unique_list = remove_duplicates_using_set(lst)
print("Unique elements:", unique_list)

In [10]:
l1={1,2,3,9,8,7}
l2={1,2,3,5,6}
print(l1.difference(l2))
print(l1.union(l2))
print(l1.intersection(l2))
print(l1.symmetric_difference(l2))

{8, 9, 7}
{1, 2, 3, 5, 6, 7, 8, 9}
{1, 2, 3}
{5, 6, 7, 8, 9}


In [1]:


print("darshan")
print(type("darshan"))

darshan
<class 'str'>


In [3]:
print(type(2027))
print(type("darshan"))
print(type(76.7676))
print(type(True))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'bool'>


In [4]:
a=2029
b="darshan"
c=True
d=2027.2727
e=676+87j
print(type(a))
print(type(b))
print(type(b))
print(type(c))
print(type(d))
print(type(e))

<class 'int'>
<class 'str'>
<class 'str'>
<class 'bool'>
<class 'float'>
<class 'complex'>


In [7]:
a="darshan"
A="darshan  good  morning"
print(a)
print(A)
_="darshan"
print(_)
_=2027
__=27
print(_+__)

darshan
darshan  good  morning
darshan
2054


In [ ]:
#comments  in  python  comments  are   ignored  by  the  comipler
#it   supports  BODMAS rule
#B=Bracket
#O=order
#D=division
#m=minus
#A=add
#s=sUbtraction


In [18]:
print(type(2027))
print(type(2027.654))
print(type("adrsgahn"))
print(type(23+2j))
print(type(True))
l=[1,2,3,4,5,6,7,8,98,76,1,2,3,4,54,5,3,4,"darshan",234.55,True]
print(type(l))
print(l)
t=(10,20,30,40,50,60,12,10,20,True,"daeshan")
print(type(t))
s={10,20,30,40,50,10,20,30,40,"darshan",True}
print(s)
print(type(s))
d={1:"sunday",2:"monday",3:"tuesday",3:"darshan"}
print(type(d))
print(d)

<class 'int'>
<class 'float'>
<class 'str'>
<class 'complex'>
<class 'bool'>
<class 'list'>
[1, 2, 3, 4, 5, 6, 7, 8, 98, 76, 1, 2, 3, 4, 54, 5, 3, 4, 'darshan', 234.55, True]
<class 'tuple'>
{'darshan', True, 50, 20, 40, 10, 30}
<class 'set'>
<class 'dict'>
{1: 'sunday', 2: 'monday', 3: 'darshan'}


In [33]:
#arithmetic  operators
print(2023+2027)
print(2023-2027)
print(2023*2027)
print(63/7)
print(62//7)
print(-5//2)
print(-7//2)
print(2**2)
print(3**3)
print(2023%2)
print(50%3)
print(100%7)
x=20
y=30
print(not(x>10  and y<2))

4050
-4
4100621
9.0
8
-3
-4
4
27
1
2
2
True


In [37]:
a=10
print(a)
a+=3
print(a)
print(~20)
print(~-20)


10
13
-21
19


In [38]:
print(~19)

-20


In [8]:
if True:
    print("darshan  good  morning")
else:
    print("bye bye darshan")

darshan  good  morning


In [9]:
if False:
    print("darshan  good  morning")
else:
    print("bye bye darshan")

bye bye darshan


In [10]:
a=29
if a%2==0:
    print("  even")
else:
    print("odd")

odd


In [15]:
a="darshan GOOD MORNING"
print(a)
print(type(a))
print(a.lower())
k=a.upper()
print(k)
print(a.capitalize())



darshan GOOD MORNING
<class 'str'>
darshan good morning
DARSHAN GOOD MORNING
Darshan good morning


In [16]:
a='darshan'  #   single  line  quotes
b="darshan"  #  
c='''hghsghvghv
mbmbn'''
print(a)
print(b)
print(c)

darshan
darshan
hghsghvghv
mbmbn


In [17]:
a=90
if a==0:
    print("zero")
elif a>0:
    print("positive")
else:
    print("negative")

positive


In [19]:
a="darshabnnn!@#$#$)(*^)"
print(a.strip("(*&^%$#@!)"))

darshabnnn


In [24]:
a="darshan####"
print(a.strip("#"))
b="****darshan&&&&"
print(b.lstrip("*"))
print(b.rstrip("&"))
print(b.strip("&*"))

darshan
darshan&&&&
****darshan
darshan


In [26]:
a,b=2028,20290
print(a,b)
a,b=b,a
print(a,b)

2028 20290
20290 2028


DAY - 2

In [2]:
for  i  in  range(2,10,2):
    print(i,end=" ")

2 4 6 8 

In [28]:
a=2027
b=3
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)#floor division
print(a%b)#reminder

2030
2024
6081
675.6666666666666
675
2


In [3]:
a=9
b=3
print(a**b)# porwer

729


In [30]:
#comparision  operators   in  python 
a=20
b=30
print(a==b)
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)
print(a!=b)


False
False
False
True
True
True


In [31]:
a=20
if a>=18:
    print("eligible  to  vote")
else:
    print("  not  eligible  to  vote")

eligible  to  vote


In [32]:
#logical  operators  in  python
a=9
b=7
if a==b and a>b:
    print("a")
elif a==b or b<a:
    print('b')
else:
    print('darshan')

b


In [4]:
import time as t
n=10
while n>0:
    print(n)
    n=n-1
    t.sleep(1)

10
9
8
7
6
5
4
3
2
1


        DAY-3

In [ ]:
#DSA CONCEPTS
#LIST
#TUPLE
#DICTIONARY
#SET


LIST


In [5]:
#   we    can  add  and  delete  elemets  easily   update  data   easily
#in  list  it  can  stores  the  different  types  of   datatypes
l=["dartshan",True,False,"darshan",67787,98.87]
print(type(l))
l.append("anvi")
print(l)
#  in  list  order  is   always  maintained
# index  valued  can  acces  easily
s=[10,29,38,"darshan",True]
print(s[::])
print(type(l))

<class 'list'>
['dartshan', True, False, 'darshan', 67787, 98.87, 'anvi']
[10, 29, 38, 'darshan', True]
<class 'list'>


In [38]:
print(s[::-1])

[True, 'darshan', 38, 29, 10]


In [39]:
s.extend([1,2,3,4,5,6,7,8])
print(s)

[10, 29, 38, 'darshan', True, 1, 2, 3, 4, 5, 6, 7, 8]


In [40]:
s.insert(1,'prajval')
print(s)

[10, 'prajval', 29, 38, 'darshan', True, 1, 2, 3, 4, 5, 6, 7, 8]


In [41]:
del s[0]
print(s)

['prajval', 29, 38, 'darshan', True, 1, 2, 3, 4, 5, 6, 7, 8]


TUPLE

In [46]:
#  in  tuple   doesnot  allow   the   add or  delete  or  update   existing  data
#   once  created   we cannot  addd  delete  and  update  the   data  existing     tuple
t=(1,2,3,4,87,9,8,7,9,8,7)
print(t)
t=('darshan',887,998,True)
print(t)
print(type(t))

(1, 2, 3, 4, 87, 9, 8, 7, 9, 8, 7)
('darshan', 887, 998, True)
<class 'tuple'>


DICTIONARY

In [49]:
#  order  is  not  maintained 
#  here  doesnot  allow    diuplicate   key  values
#allowes  the  duplicate   values  but  not  not  keys
d={1:"darshan",2:"amar"}
print(d)
print(type(d))
print(d.keys())
print(d.values())

{1: 'darshan', 2: 'amar'}
<class 'dict'>
dict_keys([1, 2])
dict_values(['darshan', 'amar'])


BREAK  IN  PYTHON

In [13]:
for i  in range(1,10,1):
    if i%2==0:
        print(i,end=" ")
        pass

2 4 6 8 

PASS  KEYWORD  IN  PYTHON

In [15]:
for i  in range(1,10,1):
    if i>=3:
        print(i,end=" ")
        continue

3 4 5 6 7 8 9 

PRIME NUMBER   OR  NOT IN  PYTHON

In [58]:
n=2027
k=0
for i  in  range(2,n):
    if n%i==0:
        k=1
if k==1:
    print('  nor  prime  number')
else:
    print('  prime number')

  prime number


SET  IN  PYTHON

In [ ]:
#  in  sets    does  not   allow  duplicate  valyes   but  in  sets  order  is  not  maintained 

In [65]:
s={1,2,3,4,5,6,79,9,9,'darshan'}
print(s)
print(type(s))
k={1,2,3,4,5,6,7,8,9,1,2,3,45,6,7,8}
print(k)
k.add(2028)
print(k)
k.remove(1)
print(k)
k.pop()
print(k)

{1, 2, 3, 4, 5, 6, 9, 79, 'darshan'}
<class 'set'>
{1, 2, 3, 4, 5, 6, 7, 8, 9, 45}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 2028, 45}
{2, 3, 4, 5, 6, 7, 8, 9, 2028, 45}
{3, 4, 5, 6, 7, 8, 9, 2028, 45}


In [66]:
l=[1,2,3,4,5,6,6,5,4,3,21,1]
m=list(set(l))
print(m)

[1, 2, 3, 4, 5, 6, 21]


METHODS  IN  SET

In [74]:
a={1,2,3,4,5}
b={2,3,4,5,6,7,8,9}
print(a.difference(b))
print(a.union(b))
print(a.intersection(b))
print(a.isdisjoint(b))
print(a.issubset(b))
print(a.symmetric_difference(b))

{1}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{2, 3, 4, 5}
False
False
{1, 6, 7, 8, 9}


In [36]:
li=[1,2,3,4,5,6,7,8,1,1,1,1,1]
n=len(li)
ones=[]
cont=0
print(n)
ans=0
for i in range(n):
    if li[i]==1:
        cont=cont+1
        ones.append(li[i])
#print(ones)
for i in range(n):
    if li[i]!=1:
        ones.append(li[i])
print(ones)
print("occurance of 1 :\n",cont)
print(" nor  occurance 1 : \n",n-cont)

13
[1, 1, 1, 1, 1, 1, 2, 3, 4, 5, 6, 7, 8]
occurance of 1 :
 6
 nor  occurance 1 : 
 7


In [37]:
ar=[1,2,90,87,65,54,423,56,43,27]
key=27
k=len(ar)
print(k)

def arry():
    for i in range(k):
       if ar[i]==key:
           return i
    else:
           return -1
print(arry())
    
      
   

10
9


In [38]:
ar=[10,20,30,49,56,78,65,45,32,16]
l=len(ar)
max(ar)
s=0
for i in range(l):
    s=s+ar[i]
print(s)


401


swapping


In [39]:

a=2027
b=2023
c=2029
print("before swaping:",a,b)
a,b,c=b,c,a
print(a,b,c)

before swaping: 2027 2023
2023 2029 2027


find MIN MAX


In [11]:
a=[2027,203,29]
k=a[0]
l=len(a)
for i in range(l):
    if a[i]<k:
        k=a[i]
print(k)

29


In [41]:
a=[2027,2023,2003,1987,2090]
max1=a[0]
l=len(a)
for k in  range(l):
    if max1<a[k]:
        max1=a[k]
print(max1)
#print(max(a))

2090


SUM OF NATURAL NUMBERS


In [42]:
n=10
s=0
for i in range(n+1):
    s=s+i
print(s)

55


In [43]:
n1=10
n2=20
s=0
for i in range(n1,n2+1):
    s=s+i
print(s)

165


Leap Year

In [44]:
year=1976
if((year%4==0 and year%100!=0 or year%400==0)):
    print("leap year")
else:
    print("normal year")


leap year


SEPARATE DATATYPE


In [18]:
values=[True,False,1,2,2,3,4,4,'ddsds',"dareshan",1212,"darshan","anvar",False,True,889.87]
li=[]
ls=[]
lb=[]
lf=[]
l=len(values)
for value in values:
    if(type(value)==int):
        li.append(value)
    if(type(value)==float):
        lf.append(values[value])
    if(type(value)==str):
        ls.append(values[value])
    if(type(value)==bool):
        lb.append(values[value])
print("list  of  integers:",li)
print('list of  strings:',ls)
print('list of  boolean:',lb)
print('list of  decimals:',lf)

TypeError: list indices must be integers or slices, not str

In [24]:
values=[True,False,1,2,2,3,4,4,'ddsds',"dareshan",1212,"darshan","anvar",False,True,889.87]
li=[]
ls=[]
lb=[]
lf=[]
for val in values:
    if type(val)==bool:
        lb.append(val)
    if type(val)==int:
        li.append(val)
    if type(val)==float:
        lf.append(val)
    if type(val)==str:
        ls.append(val)
    
print(lb)
print(ls)
print(li)
print(lf)

[True, False, False, True]
['ddsds', 'dareshan', 'darshan', 'anvar']
[1, 2, 2, 3, 4, 4, 1212]
[889.87]


PRIMENUMBERS


In [46]:
num=2027
f=0
for i in range(2,num):
    if num%i==0:
        f=1
        break
if f==1:
    print("not prime")
else:
    print("prime")

prime


In [26]:
def prime():
    num=20272
    for i in range(2,num):
        if num%i==0:
            return False
        else:
            return  True
prime()
    

False

In [47]:
n1=2027
n2=2023
print(n1+n2)
k=n1+n2
print(k)

print("darshan good  morning")

4050
4050
darshan good  morning


In [27]:
p=64
#s=p**(0.5)
s=p**(1/4)
print(s)
import math
n=25
k=math.sqrt(n)
print(k)

2.8284271247461903
5.0


In [49]:
b=12.3
h=98
a=0.5*b*h
print(a)


602.7


In [50]:
a=2029
b=20290
a,b=b,a
print(a,b)
p=2027
q=2028
t=p
p=q
q=t
print(p,q)

20290 2029
2028 2027


In [36]:
n=2
import random
k=random.randrange(0,7)
if k==n:
    print("you win the  match")
else:
    print(" not")
print(k)

you win the  match
2


In [52]:
km=23
mil=float(23*0.61761)
print(mil)

14.20503


degree to  farenheit


In [53]:
c=37
f=(c*1.8)+32
print(f)

98.60000000000001


In [54]:
num=-98
if  num==0:
    print("zero")
elif num>0:
    print("positive")
else:
    print("negative")

negative


In [55]:
num=98
if  num==0:
    print("zero")
elif num%2==0:
    print("even")
else:
    print("odd")

even


In [56]:
year=200
if((year%4==0 and year%100!=0)or(year%400==0)):
    print("leap year")
else:
    print("normal year")

normal year


In [57]:
n1=2023
n2=209877
n3=98765
max1=0
if n1>n2 and n1>n3:
    max1=n1
elif n2>n1 and n2>n3:
    max1=n2
else:
    max1=n3
print(max1)

209877


In [58]:
low=20
upp=300
for num in range(low,upp+1):
    if num>1:
        for i in range(2,num):
            if num%i==0:
                break
        else:
            print(num," ",end='')

23  29  31  37  41  43  47  53  59  61  67  71  73  79  83  89  97  101  103  107  109  113  127  131  137  139  149  151  157  163  167  173  179  181  191  193  197  199  211  223  227  229  233  239  241  251  257  263  269  271  277  281  283  293  

In [59]:
n1=2023
n2=209877
n3=98765
max1=n1
if n1>n2 and n1>n3 and n2>n3:
    max1=n1
    print(max1)

elif n2>n1 and n2>n3:
    max1=n2
else:
    max1=n3
print(max1)

209877


In [60]:
num=99871
f=0
for i in range(2,num):
    if num%i==0:
        f=1
        break
if f==1:
    print('not prime ')
else:
    print("prime")


prime


In [61]:
low=10
up=50
for i in range(low,up+1):
    if i>1:
        for k in range(2,i):
            if i%k==0:
                break
        else:
            print(i," ",end=" ")

11   13   17   19   23   29   31   37   41   43   47   

In [62]:
num=6
f=1
for k in range(1,num+1):
    f=f*k
print(f)




720


In [63]:
def fact(n):
    if n==0:
        return 1
    else:
        return n*fact(n-1)
print(fact(6))

720


In [64]:
num=27
for i in range(1,11):
    print(num,'x',i,"=",num*i)


27 x 1 = 27
27 x 2 = 54
27 x 3 = 81
27 x 4 = 108
27 x 5 = 135
27 x 6 = 162
27 x 7 = 189
27 x 8 = 216
27 x 9 = 243
27 x 10 = 270


In [65]:
num=1
n1=0
n2=1
n3=1
for i in range(0,num+1):
    print(n1,end=" ")
    n1=n2
    n2=n3
    n3=n1+n2


0 1 

Armstrong number

In [66]:
num=548834
count=0
temp=num
n=num
arm=0
while num>0:
    count=count+1
    num=num//10
print(count)
while(n>0):
    r=n%10
    arm=arm+(r**count)
    n=n//10
print(arm)
if temp==arm:
    print("armstrong number")
else:
    print('not  armstrong number')


6
548834
armstrong number


DISPLAY powers of TWO

In [67]:
terms=6
result=list(map(lambda x:2**x,range(terms+1)))
print(result,"\n")
for i in range(terms+1):
    print("2 pow",i,'is',result[i])

[1, 2, 4, 8, 16, 32, 64] 

2 pow 0 is 1
2 pow 1 is 2
2 pow 2 is 4
2 pow 3 is 8
2 pow 4 is 16
2 pow 5 is 32
2 pow 6 is 64


In [68]:
num=600
for i in range(1,num+1):
    if num%i==0:
        print(i,end=" ")

1 2 3 4 5 6 8 10 12 15 20 24 25 30 40 50 60 75 100 120 150 200 300 600 

In [69]:
dec=10
print("the conversion of  decimal number",dec,"is:")
print(bin(dec),"in binary")
print(oct(dec),"in octal")
print(hex(dec),"in hexa")

the conversion of  decimal number 10 is:
0b1010 in binary
0o12 in octal
0xa in hexa


find  the ascci charactetr


In [37]:
c='a'
print("ascii valus  :")
print(ord(c))

ascii valus  :
97


HCF AND GCD


In [71]:
n1=24
n2=68
hcf=1
max1=0
if n1>n2:
    max1=n1
else:
    max1=n2
for i in range(1,max1):
    if n1%i==0 and n2%i==0:
        hcf=i
print(hcf)
print("LCM :",(n1*n2)/hcf)


4
LCM : 408.0


In [72]:
num=32
for k in range(1,num):
    if num%k==0:
        print(k,end=" ")

1 2 4 8 16 

In [73]:
import calendar
year=1947
month=8
cal=calendar.month(year,month)
print(cal)



    August 1947
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31



Fibanocci  SERIES USING RECUSRION


In [3]:
#n=10
def fibo(n):
    if n<=1:
        return n
    else:
        return fibo(n-1)+fibo(n-2)
fibo(1)

1

In [239]:
def natural(n):
    if n<=1:
        return n
    else:
        return (n)+natural(n-1)
print(natural(10))


55


In [246]:
def factorial(n):
    if n<=1:
        return 1
    else:
        return  (n*factorial(n-1))
print(factorial(5))

120


DECIMAL TO BINARY

In [263]:
dec=31
bina=[]
while dec>0:
    r=dec%2
    bina.append(r)
    dec=dec//2
rev=bina[::-1]
print(rev)


[1, 1, 1, 1, 1]


DECIMAL TO OCTA

In [266]:
dec=48
bina=[]
while dec>0:
    r=dec%8
    bina.append(r)
    dec=dec//8
rev=bina[::-1]
print(rev)


[6, 0]


In [270]:
s=""
rev=s[::-1]
print(rev)
if rev==s:
    print("palindrome")
else:
    print("not palindrome")


palindrome


REMOVE PUNCTUATIONS

In [283]:
punc="[!@#$%^&*()+_)(&)]"
string="darshan2027how are yoy&^&^&"
empty=""
for i in string:
    if i not in punc:
        empty=empty+i
print(empty)


darshan2027how are yoy


SORT SLPHABETIC ORDER

In [304]:
s="Darhsn good Morning how  are you"
l=len(s)
w=s.split(" ")
print(w)
print(w[0])
for i in range(len(w)):
    w[i]=w[i].lower()
print(w)
w.sort()
print(w)
for i in w:
    print(i,end=' ')

['Darhsn', 'good', 'Morning', 'how', '', 'are', 'you']
Darhsn
['darhsn', 'good', 'morning', 'how', '', 'are', 'you']
['', 'are', 'darhsn', 'good', 'how', 'morning', 'you']
 are darhsn good how morning you 

SET DIFFERENT OPERATIONS


In [313]:
s1={1,2,3,4,5,6,7}
s2={9,8,7,6,5,4,3}
print(s1.difference(s2))
print(s1.union(s2))
print(s1.intersection(s2))
print(s1.symmetric_difference(s2))
print(s1.difference_update(s2))
print(s1.isdisjoint(s2))
print(s1.issubset(s2))
print("the union",s1|s2)
print("intersection ",s1&s2)
print("difference",s2-s1)
print("symmetric difference is:",s1^s2)

{1, 2}
{1, 2, 3, 4, 5, 6, 7, 8, 9}
{3, 4, 5, 6, 7}
{1, 2, 8, 9}
None
True
False
the union {1, 2, 3, 4, 5, 6, 7, 8, 9}
intersection set()
difference {3, 4, 5, 6, 7, 8, 9}
symmetric difference is: {1, 2, 3, 4, 5, 6, 7, 8, 9}


    COUNT THE NUMBER OF EACH  VOWEL

In [7]:
a='darshan Good Morning'.lower()
vowelss="aeiou"
count={}.fromkeys(vowelss,0)
for c in a:
    if c in count:
        count[c]+=1
print(count)

{'a': 2, 'e': 0, 'i': 1, 'o': 3, 'u': 0}


RESOLUTION OF  A  IMAGE

In [323]:
import PIL
from PIL import Image
import PIL.Image
img=PIL.Image.open(r"C:\Users\darsh\OneDrive\Pictures\ANVI.png")
width,height=img.size
print(width,"X",height)

1870 X 894


MERGE TWO DICTIONARY


In [11]:
dict1={"darshan":98,"anvith":99}
dict2={"darshan":98,"deepak":96}
print(dict1|dict2)
print({**dict1,**dict2})

{'darshan': 98, 'anvith': 99, 'deepak': 96}
{'darshan': 98, 'anvith': 99, 'deepak': 96}


CREATE NESTED DIRECTORY

In [327]:
from pathlib import Path
Path("C:/Users/darsh/OneDrive/202327/new_dict/demo/dict").mkdir(parents=True)

FIND INDEX  OF  THE  ELEMEnt


In [333]:
ls=[12,34,555,67,98]
for i,val in enumerate(ls,start=1):
    print(i,val)
print("\n")
lp=[90,87,76,64,43]
for i in range(len(lp)):
    value=lp[i]
    print(i,value)




1 12
2 34
3 555
4 67
5 98


0 90
1 87
2 76
3 64
4 43


    SLICE LIST IN PYTHON

In [342]:
ls=["darshan","darsh","anvith","ram","ramya"]
print(ls[::-1])
print(ls[:])
print(ls[:2])
print(ls[:-2])
print(ls[-1:])
print(ls[::])
print(ls[:3])
print(ls[2:])
print(ls[::2])
#C:\Users\darsh\OneDrive\Desktop\202327\PYTHONCOURSE\PYTHONDSA

['ramya', 'ram', 'anvith', 'darsh', 'darshan']
['darshan', 'darsh', 'anvith', 'ram', 'ramya']
['darshan', 'darsh']
['darshan', 'darsh', 'anvith']
['ramya']
['darshan', 'darsh', 'anvith', 'ram', 'ramya']
['darshan', 'darsh', 'anvith']
['anvith', 'ram', 'ramya']
['darshan', 'anvith', 'ramya']


In [8]:
s="kayak"
r=s[::-1]
print(r)
if s==r:
    print("palindrome")
else:
    print("  not pali")

kayak
palindrome


SLICE LIST

In [345]:
friend={"darshan":20,"anvi":1433,"ram":987}
print(friend)
for key,value in friend.items():
    print(key,":",value)




{'darshan': 20, 'anvi': 1433, 'ram': 987}
darshan : 20
anvi : 1433
ram : 987


In [16]:
s="kayak"
print(s[::-1])
print(s[::-2])
print(s[::3])
s="darshan goodmorning"
print(s[:])
print(s[1:])
print(s[::2])
print(s[2:6:2])
print(s[2:6:])
print("  darshan")
print(s[2:6:])
print(s[::-1])

kayak
kyk
ka
darshan goodmorning
arshan goodmorning
drhngomrig
rh
rsha
  darshan
rsha
gninromdoog nahsrad


In [19]:
s="hello good morning"
print(s[::-1])
print(s[::-2])
print(s[:6:-1])

gninrom doog olleh
girmdo le
gninrom doo


SORT DICTIONAR by  values

In [349]:
ds={1:"darshan",2:"anvi"}
print(ds.keys())
sv=sorted(ds.items(),key=lambda x:x[1])
print(sv)

dict_keys([1, 2])
[(2, 'anvi'), (1, 'darshan')]


CHECK LIST IS  EMPTY

In [353]:
print(bool([90,872]))
ls=[6166615171]
if not ls:
    print("the list is  empty")
else:
    print("list  is  not  empyty")
k=[]
if len(k)==0:
    print("k  is  empty")

True
list  is  not  empyty
k  is  empty


EXCEPTIONS  IN  PYTHON

In [358]:
s="darshan"
try:
    n=int(2027)

    print(s+n)
except(ValueError,TypeError) as a:
    print("occur  error")
    print("thank you")
  


occur  error
thank you


In [359]:
l1=[90,98,76,"dsrhna","darshan","deeraj"]
l2=[902,981,7698,"dsrhna","darshan","deeraj"]
print(l1+l2)

[90, 98, 76, 'dsrhna', 'darshan', 'deeraj', 902, 981, 7698, 'dsrhna', 'darshan', 'deeraj']


In [364]:
names={'darshan':1,"feepak":2,"amar":3,"amulya":5}
n="darshan"
if n in names.keys():
    print("it  is  present")
else:
    print("it  is  not  present")

it  is  present


STRING  TO INT FLOAT

In [368]:
s="2027"
print(type(s))
k=int(s)
print(type(k))

<class 'str'>
<class 'int'>


In [405]:
import datetime
from datetime import datetime
date="oct 14 1997 7:18AM"
dt=datetime.strptime(date,"%b %d %Y %I:%M%p")
print(dt)
k=datetime.now()
print(k)
print(type(datetime))


1997-10-14 07:18:00
2024-09-24 17:10:45.068701
<class 'type'>


GET  THE  LAST  ELEEMNST  OF  THE LIST

In [406]:
ls=[90,87,65,65,45,43,21]
print(ls[-1])


21


SUBSTRING OF  A  ARRAY

In [408]:
a="darshan  good  morning"
print(a[:13])

darshan  good


In [410]:
f=open("hello.txt",'r')
lines=f.readlines()
print(lines)
nline=[x.strip() for x in lines]
print(nline)

['darshan 76\n', 'amar    98\n', 'akbar   98\n', 'anthoni 88']
['darshan 76', 'amar    98', 'akbar   98', 'anthoni 88']


In [412]:
ls=[10,20,30,40,50,10]
k=ls.count(10)
print(k)

2


In [414]:
f=open("hello.txt",'a')
f.write("darshan this  is your personal")
f.close()
#   a  is  mainly  is  used  to  append  the  data


In [415]:
names={'darshan':1,"feepak":2,"amar":3,"amulya":5}
del names["darshan"]
print(names)

{'feepak': 2, 'amar': 3, 'amulya': 5}


In [416]:
print('''tefdyehygdv
      vwhvxhwvghv''')

tefdyehygdv
      vwhvxhwvghv


In [418]:
import os
fs=os.path.splitext(r"C:\Users\darsh\OneDrive\202327\JAVACOURSE\ARRAYS\arrayoperations.java")
print(fs[-1])

.java


In [422]:
s="  darshan  good morning "
print(s.strip(" "))

darshan  good morning


In [1]:
n=87897
print(n)
print(type(n))

87897
<class 'int'>


In [3]:
x="darshan"
y="deepak"
z="ramya"
print(x,y,z)
len(x)

darshan deepak ramya


7

STRING METHODS IN  PYTHON


In [16]:
s="darshan"
print(s)
len(s)
print(s[1])
print(s[1:])
print(s[1:4])
print(s[:])
print(s[::-1])
print(s[-6::])
print(s[1:5])
print(s.upper())
print(s.lower())
print(s[0])

darshan
a
arshan
ars
darshan
nahsrad
arshan
arsh
DARSHAN
darshan
d


    LIST TYPE

In [25]:
# ordered  can  be changed   duplicate  entries  are  present
ls=[10,29,38,46,10,29,37,"darshan"]
ls
ls[2]
print(ls)
ls[2]="darshan"
print(ls)
ls.append("anvi")
print(ls)
ls.insert(5,"rajkumar")
print(ls)

[10, 29, 38, 46, 10, 29, 37, 'darshan']
[10, 29, 'darshan', 46, 10, 29, 37, 'darshan']
[10, 29, 'darshan', 46, 10, 29, 37, 'darshan', 'anvi']
[10, 29, 'darshan', 46, 10, 'rajkumar', 29, 37, 'darshan', 'anvi']


DICTIONARY   UNORDERED  CAN  BE CHANGED  NO  DUPLICATE  ENTRIES  ARE PRESENT  key  value


In [28]:
#values  in  key  may  be   duplicate
c={1:"java",
   2:"python",
   3:"darshan"}
print(c)
print(c.keys())
print(c.get(1))

{1: 'java', 2: 'python', 3: 'darshan'}
dict_keys([1, 2, 3])
java


ORDERD  CANNOT BE  CHANGED DUPLICATE  ENTRIES ARE  PRESENT

In [35]:
t=("darshan","tiger","amrutha","anvitha","rashmi",983,65,87,987)
print(t)
t.count("darshan")
print(t.index("anvitha"))


('darshan', 'tiger', 'amrutha', 'anvitha', 'rashmi', 983, 65, 87, 987)
3


SET UNORDERRD NO  DUPLICATES ARE PRESENT


In [77]:
sets={20,12,13,14,10,10,10}
print(sets)

{20, 10, 12, 13, 14}


In [78]:
list(range(20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [80]:
x="darshan"
y=2027
print(x+str(y))

darshan2027


    COLLECTIONS IN PYTHON

LISTS
TUPLES
SETS
DICTIONARY

In [90]:
import array as ar
a=ar.array('i',[1,2,3,4,5,6,7])
print(a)

array('i', [1, 2, 3, 4, 5, 6, 7])


In [4]:
n=21
if n&1==0:
    print("even")
else:
    print("odd")

odd


In [8]:
#left shift  of  any  number  once  the  out  put  is  twice  a  given  number
#a<<1==2a
#a<<b=a*2pow(b)
print(4<<1)

print(40<<1)
print(5<<2)
print(6<<6)


8
80
20
384


In [12]:
ord('0')
print(bin(10))
print(hex(10))
print(oct(10))

0b1010
0xa
0o12


STRINGS

In [4]:
s="darshan"
print(type(s))
s1='darshan'
s2="""darshan"""
s3='''darshan
darshan good  morning'''
print(s1)
print(s2)
print(s3)

<class 'str'>
darshan
darshan
darshan
darshan good  morning


In [11]:
s="darshan"
print(s[0])
print(s[-1])
print(s[3:-1])
print(s[::-1])
k=s[::-1]
print(k)

d
n
sha
nahsrad
nahsrad


In [1]:
s="darshan good  morning"
k=s.split(" ")
reverse=" "
for i  in range(len(s)):
    for k in range(len(k)):
        rev=""
        

print(k)


['darshan', 'good', '', 'morning']


In [12]:
w="darshan goodmorning amar akbar".split(" ")
print(len(w))
reverse="  "
for k in range(len(w)):
    rev=w[k][::-1]
    reverse=reverse+rev+" "
rev=w[::-1]
print(rev)
print(reverse)

4
['akbar', 'amar', 'goodmorning', 'darshan']
  nahsrad gninromdoog rama rabka 


In [18]:
k="darshan good morning"
print(k.split(" "))
for i in range(len(k)):
    print(k[i],end=" ")

['darshan', 'good', 'morning']
d a r s h a n   g o o d   m o r n i n g 

In [24]:
n=28
s=0
for i in range(1,n):
    if n%i==0:
        #print(i,end=" ")
        s=s+i
if s==n:
    print("perfect number")
else:
    print("not perfect number")
print(s)


perfect number
28


FILE HANDLING CONCEPT


In [1]:
#  WHAT  IS  FILE WHY  WE  NEED  TO  FILE

'''  file  isnnnothing  but    name  of  the  memory  location of  disc   that  stores  data  permentally

file  handling  ?
file  handiling  is  a mechanicm   through   which   we  can
  create
  write
  read
  copy
  delete
  


'''
print("darshan")


darshan


In [ ]:
#create  read copy  delte
'''
x  :  create  a  new  file
w  : write  something  a  new  file
r  :  read  the file
r+ :  read  and  write  both
a  :  append
'''

In [2]:
#create  a  file
k=open("abc",'x')



In [6]:
#writting  in  the  file  
f=open("hello.txt",'w')
#  w  is  the  write  mode
f.write("prjval  good  morning")
#  write  mode  it  will  remove  previous  written  info  and  re  write  the  file   with  new  file
#  x    will  be  used  for  vreating  the  new  file
print("data write  succefully")




data write  succefully


In [8]:
f=open("hello.txt",'a')
#   a  append  mode   it  helps  to  writte  the  new  linee s  without  removing  the  previous  information
f.write("\n ")


24

In [14]:
f=open("hello.txt",'r')
#  r  is  the  read  mode 
print(f.read(90))


prjval  good  morningdarshan  good  morning
 darshan  good  morning


In [15]:
f=open("hello.txt",'r')
#  r  is  the  read  mode 
print(f.readline())#  this  will  prints  the  first  line  of  the  file)


prjval  good  morningdarshan  good  morning



In [17]:
f=open("hello.txt",'r')
#  r  is  the  read  mode 
info=f.readlines()#  save  the  information  in  the  file
print(f.readlines())
#  all  the  data    stored  in  that  file  displaya



[]


In [18]:
print(info)

#  all  the  sores  in  the  form  of  list


['prjval  good  morningdarshan  good  morning\n', ' darshan  good  morning']


In [19]:
info

['prjval  good  morningdarshan  good  morning\n', ' darshan  good  morning']

In [28]:
st="\n".join(info)
#   int  that " "  it   mainly  used  to   waht  we  need   to  add   inbetweeb  the two  lines  space  data
print(st)

prjval  good  morningdarshan  good  morning

 darshan  good  morning


EXCEPTION  HANDLING  CONCEPT  IN  PYTHON

In [31]:
try:
    f=open("hello123.txt",'r')
    print(f.read(90))
except:
    print("occurs  an  errors")
finally:#   it  excutes  this  is  the  use  case  of  exception  handling
    print("this  is  the  default  statement")


    
#  r  is  the  read  mode 






#finally:  it  works   according  to  the   else  statement

occurs  an  errors
this  is  the  default  statement


    COPY  FILE

In [32]:
#copy  file  from  one  file  to  another
try:
    with open("hello.txt",'r') as f2:#  r  read mode x  create  a  file a  is  the  append   mode
        with open("hello123.txt",'w') as f3:#  w  is  the  write  mode
            for i  in f2:# copying  the  text  fron  one  file   to  another  file
                f3.write(i)
    print("file  is   copied")
except:
    print(" file  is  not  found ")

finally:
    f2.close()




file  is   copied


In [33]:
print(f2)

<_io.TextIOWrapper name='hello.txt' mode='r' encoding='cp1252'>


DELETING  THE  FILE

In [ ]:
import os
if os.path.exists("hello.txt"):
    os.remove("hello.txt")
    print("file  is  removed")
else:
    print('files  is  not  found ')


DIFFRENT  TYPES  OF  FILES  

DAY-4

MODULES  AND  LIBRARIES  IN PYTHON

In [ ]:
'''                      Module: 
a  module  is  a  self  contsained  piece  of  code  that
   provides  a  specific  functionality  or  set  of   functionalities
   module  is  a  part  of  library

            library:
            library  is  a  collection  of  modules  and  classes  that  provide  a  border  range  of  functionality
            it  contains  more  number  of  modules
            every  module  is  part of  the  library

            modules:
            MATH
            datetime
   
            
            libraries :
             numpy
             pandas

'''


In [4]:
import math as m#  this  is  a   way  of  importing  the  module
#constraints  in math
print(m.pi)
print(m.sqrt(726))
print(m.tau)
print(m.log(29))
print(m.e)


3.141592653589793
26.94438717061496
6.283185307179586
3.367295829986474
2.718281828459045


In [5]:
print(m.sqrt(625))

25.0


In [7]:
r=34
a=m.pi*(r*r)
print(a)

3631.681107549801


In [8]:
round(2027.7677,3)

2027.768

In [11]:
print(m.floor(2027.23))#  rounded  ground  value
print(m.ceil(2027.23))#  roundaed  to  the upper  value


2027
2028


In [13]:
print(m.sin(45))
print(m.sin(0))
print(m.sin(30))
print(m.sin(120))
print(m.sin(90))

0.8509035245341184
0.0
-0.9880316240928618
0.5806111842123143
0.8939966636005579


In [14]:
print(m.cos(45))
print(m.cos(0))
print(m.cos(30))
print(m.cos(120))
print(m.cos(90))

0.5253219888177297
1.0
0.15425144988758405
0.8141809705265618
-0.4480736161291701


In [15]:
print(m.tan(45))
print(m.tan(0))
print(m.tan(30))
print(m.tan(120))
print(m.tan(90))

1.6197751905438615
0.0
-6.405331196646276
0.7131230097859091
-1.995200412208242


In [16]:
print(m.cosh(45))
print(m.cosh(0))
print(m.cosh(30))
print(m.cosh(120))
print(m.cosh(90))

1.7467135528742547e+19
1.0
5343237290762.231
6.520904391968161e+51
6.102016471589204e+38


In [18]:
print(m.radians(90))
print(m.radians(45))
print(m.radians(60))
print(m.radians(98))
print(m.radians(120))
print(m.radians(180))

1.5707963267948966
0.7853981633974483
1.0471975511965976
1.710422666954443
2.0943951023931953
3.141592653589793


In [ ]:
print(m.cos(45))
print(m.cos(0))
print(m.cos(30))
print(m.cos(120))
print(m.cos(90))

2024-10-01 11:29:21.510018


DATETIME

In [ ]:
'''
logging :  use  it log  the time  of  run
insert_dt  in a     database  insert recodr
converting a  string  column  to    a     date  column
date
time
datetime
timedelta


'''

In [20]:
import  datetime 
k= datetime.datetime.now()
print(k)

2024-10-01 11:32:51.037733


In [24]:
from datetime import datetime,timedelta,date,time
dt=date(2027,12,25)
print(dt)
print(type(dt))

2027-12-25
<class 'datetime.date'>


In [25]:
d='2027-12-25'
print(type(d))

<class 'str'>


In [31]:
print(dt.day)
print(dt.weekday())

print(dt.year)

25
5
2027


In [38]:
from datetime import date,time
k=time(11,40,45)
print(k)
print(k.hour)
print(k.second)
print(k.minute)

11:40:45
11
45
40


In [40]:
import datetime
xms=timedelta(days=10)
xms+timedelta(days=100)

datetime.timedelta(days=110)

In [45]:
k=datetime.datetime.now()
print(k)

2024-10-01 11:46:36.793693


In [50]:
import numpy as np
l=[1,2,3,4,5,6,7]
s=[9,8,7,6,5,4,3]
k=s+l
print(s+l)
print(k)
total=[]
for i in range(len(k)):
    sum=k[i]
    total.append(sum)
print(sum)

[9, 8, 7, 6, 5, 4, 3, 1, 2, 3, 4, 5, 6, 7]
[9, 8, 7, 6, 5, 4, 3, 1, 2, 3, 4, 5, 6, 7]
7


In [ ]:
a1=[1,2,3,4,5,6]

In [12]:
import math as m
print(m.floor(2027.27))
print(m.ceil(2027.27))
print(m.log(10))
print(m.sqrt(25))
print(m.fabs(2))
print(m.isnan(2027))
print(m.isnan(0))
print(m.log1p(10))
print(m.log10(20))

2027
2028
2.302585092994046
5.0
2.0
False
False
2.3978952727983707
1.3010299956639813


In [14]:
print(m.factorial(5))
print(m.tan(45))

120
1.6197751905438615


In [42]:
from datetime import date,time,datetime
k=datetime.now()
print(k)
print(k.hour)
print(k.minute)
print(k.second)
print(k.microsecond)
print(k.weekday())
print(k.astimezone())
#print(k.fromisocalendar(2027))
print(k.today())

2024-10-02 05:46:36.660083
5
46
36
660083
2
2024-10-02 05:46:36.660083+05:30
2024-10-02 05:46:36.661041


In [44]:
import  numpy  as  np
import pandas   as  pd
ser=pd.Series()
print(ser)
data=np.array(['d','a','r','s','h','a','n'])
ser=pd.Series(data)
print("pandas  series: ",ser)

Series([], dtype: object)
pandas  series:  0    d
1    a
2    r
3    s
4    h
5    a
6    n
dtype: object


In [45]:
ls=["darshan","prajwal","amar",'akbar','anthoni']
pf=pd.DataFrame(ls)
print(pf)

         0
0  darshan
1  prajwal
2     amar
3    akbar
4  anthoni


In [46]:
data=pd.Series([1,2,3,4,5],index=["darshan","amar","ram","suresh","hanuman"])
print(data)
print(type(data))

darshan    1
amar       2
ram        3
suresh     4
hanuman    5
dtype: int64
<class 'pandas.core.series.Series'>


In [47]:
data={'name':["darshan","hanuman","ram","rahul"],
      'degree':["BE","BCA","MTECH","MBA"],
      'score':[90,98,987,86]}
df=pd.DataFrame(data)
print(df)
print(type(df))

      name degree  score
0  darshan     BE     90
1  hanuman    BCA     98
2      ram  MTECH    987
3    rahul    MBA     86
<class 'pandas.core.frame.DataFrame'>


In [48]:
data={'Name':['vinay', 'vishal', 'amar', 'akbar'], 
        'Age':[27, 24, 22, 24], 
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'], 
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']} 
print(data)
df=pd.DataFrame(data)
df["Name"]=df["Name"].str.lower()
print(df)

{'Name': ['vinay', 'vishal', 'amar', 'akbar'], 'Age': [27, 24, 22, 24], 'Address': ['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'], 'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}
     Name  Age    Address Qualification
0   vinay   27      Delhi           Msc
1  vishal   24     Kanpur            MA
2    amar   22  Allahabad           MCA
3   akbar   24    Kannauj           Phd


In [ ]:
data=pd.read_csv("C:\Users\darsh\OneDrive\202327\PYTHONCOURSE\sample.csv")
data['Name']=data["Age"].str.upper()
print(data)

In [50]:
s=pd.Series(["d",'a','r','s','h','a','n'])
n=s.str.extract(r'([ab])(\d)')
print(n)

     0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN
3  NaN  NaN
4  NaN  NaN
5  NaN  NaN
6  NaN  NaN


In [51]:
import pandas as p
df=p.DataFrame()
print(df)
print(type(df))

Empty DataFrame
Columns: []
Index: []
<class 'pandas.core.frame.DataFrame'>


In [ ]:
ls=["darshan","prajwal","ram",'hanuman']
df=p.DataFrame(ls)
print(df)

In [ ]:
data={'name':['darshan',"amar","akbar","anthoni","hanuman"],'age':[10,20,39,47,50]}
df=p.DataFrame(data)
print(df)

In [ ]:
data={'name':["darshan","prajwal","amar",'akbar',"veeraj"],
      'degree':["bca",'btech','be',"bsc","bpharmacy"],
      'score':[10,29,39,48,67]}
df=p.DataFrame(data)
print(df)

In [54]:
import  numpy as n
arr=n.array([1,2,3,4,5,6])
print("array  with rank : \n ",arr)
print(arr)

array  with rank : 
  [1 2 3 4 5 6]
[1 2 3 4 5 6]


In [53]:
n="malayalam"
rev=n[::-1]
if rev==n:
    print("pali")
else:
    print("not pali")
# print(rev)

pali


In [52]:
n1=2027
n2=2023
print("before  swapping : \n n1:",n1,"\n n2:",n2)
n1,n2=n2,n1
print("after swapping : \n n1:",n1,"\n n2:",n2)


before  swapping : 
 n1: 2027 
 n2: 2023
after swapping : 
 n1: 2023 
 n2: 2027


EXCEPTIO  HANDLING   CONCEPTS

In [28]:
try:
    n1=2027
    n2=0
    print(n1/n2)
except ZeroDivisionError:
    print(" error  cannot  divide  by  zero")

 error  cannot  divide  by  zero


In [4]:
try:
    f=open("helloh.txt",'r')
    c=f.read()
    print(f)
except FileNotFoundError:
    print("file not found")

file not found


In [7]:
try:
    num=int("dar")#inside  the  sting  it  contains   only integers string
    print(num)
except:
    print("  string  cannot   convert  to  int")


  string  cannot   convert  to  int


In [14]:
try:
    file = open("hello.txt", "r")
    content = file.read()
    print(content)
    num = int("2027")  # Raises a ValueError
    print(num)
except FileNotFoundError:
    print("File not found.")
except ValueError:
    print("Invalid input: Cannot convert string to integer.")


prjval  good  morningdarshan  good  morning
 darshan  good  morning
2027


In [1]:
print("darshan")

darshan


MATH MODULE IN PYTHON

In [4]:
import math

# Trigonometric functions
print("Trigonometric functions:")
print(math.sin(math.pi / 2))  # Sine of 90 degrees
print(math.cos(math.pi))  # Cosine of 180 degrees
print(math.tan(math.pi / 4))  # Tangent of 45 degrees
print(math.asin(1))  # Arcsine of 1
print(math.acos(0))  # Arccosine of 0
print(math.atan(1))  # Arctangent of 1

# Hyperbolic functions
print("\nHyperbolic functions:")
print(math.sinh(0))  # Hyperbolic sine of 0
print(math.cosh(0))  # Hyperbolic cosine of 0
print(math.tanh(1))  # Hyperbolic tangent of 1
print(math.asinh(0))  # Inverse hyperbolic sine of 0
print(math.acosh(1))  # Inverse hyperbolic cosine of 1
print(math.atanh(0))  # Inverse hyperbolic tangent of 0

# Logarithmic functions
print("\nLogarithmic functions:")
print(math.log(10))  # Natural logarithm of 10
print(math.log10(100))  # Base-10 logarithm of 100
print(math.log2(8))  # Base-2 logarithm of 8

# Exponential functions
print("\nExponential functions:")
print(math.exp(1))  # Exponential function of 1
print(math.expm1(1))  # Exponential function minus 1
print(math.log1p(1))  # Natural logarithm of 1+x

# Power and root functions
print("\nPower and root functions:")
print(math.pow(2, 3))  # 2 raised to the power of 3
print(math.sqrt(25))  # Square root of 25
print(math.factorial(5))  # Factorial of 5

# Ceiling and floor functions
print("\nCeiling and floor functions:")
print(math.ceil(3.14))  # Ceiling of 3.14
print(math.floor(3.14))  # Floor of 3.14

# Rounding functions
print("\nRounding functions:")
# print(math.round(3.14),2)  # Rounding to the nearest integer
print(math.trunc(3.14))  # Truncating the decimal part

# Constants
print("\nConstants:")
print(math.pi)  # Pi
print(math.e)  # Euler's number

Trigonometric functions:
1.0
-1.0
0.9999999999999999
1.5707963267948966
1.5707963267948966
0.7853981633974483

Hyperbolic functions:
0.0
1.0
0.7615941559557649
0.0
0.0
0.0

Logarithmic functions:
2.302585092994046
2.0
3.0

Exponential functions:
2.718281828459045
1.718281828459045
0.6931471805599453

Power and root functions:
8.0
5.0
120

Ceiling and floor functions:
4
3

Rounding functions:
3

Constants:
3.141592653589793
2.718281828459045


DATE TIME MODULE IN PYTHON

In [5]:
import datetime

# Time-related functions
print("Time-related functions:")
print(datetime.time())  # Current time
print(datetime.time(hour=12, minute=30, second=45))  # Specific time
print(datetime.time.min)  # Minimum time
print(datetime.time.max)  # Maximum time

# Date-related functions
print("\nDate-related functions:")
print(datetime.date.today())  # Current date
print(datetime.date(2023, 12, 25))  # Specific date
print(datetime.date.min)  # Minimum date
print(datetime.date.max)  # Maximum date

# Datetime functions
print("\nDatetime functions:")
print(datetime.datetime.now())  # Current datetime
print(datetime.datetime(2023, 12, 25, 12, 30, 45))  # Specific datetime
print(datetime.datetime.fromtimestamp(0))  # Datetime from timestamp
print(datetime.datetime.utcnow())  # Current UTC datetime

# Timedelta functions
print("\nTimedelta functions:")
timedelta = datetime.timedelta(days=3, hours=5, minutes=10)
print(timedelta)
print(datetime.datetime.now() + timedelta)  # Adding timedelta to current datetime
print(datetime.datetime.now() - timedelta)  # Subtracting timedelta from current datetime

# Formatting functions
print("\nFormatting functions:")
print(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))  # Formatting datetime
print(datetime.datetime.strptime("2023-12-25 12:30:45", "%Y-%m-%d %H:%M:%S"))  # Parsing datetime string

# Other functions
print("\nOther functions:")
print(datetime.datetime.utcfromtimestamp(0))  # UTC datetime from timestamp
print(datetime.datetime.fromisoformat("2023-12-25T12:30:45"))  # Parsing ISO 8601 formatted datetime

Time-related functions:
00:00:00
12:30:45
00:00:00
23:59:59.999999

Date-related functions:
2024-10-02
2023-12-25
0001-01-01
9999-12-31

Datetime functions:
2024-10-02 15:25:20.930901
2023-12-25 12:30:45
1970-01-01 05:30:00
2024-10-02 09:55:20.930901

Timedelta functions:
3 days, 5:10:00
2024-10-05 20:35:20.930901
2024-09-29 10:15:20.930901

Formatting functions:
2024-10-02 15:25:20
2023-12-25 12:30:45

Other functions:
1970-01-01 00:00:00
2023-12-25 12:30:45


C:\Users\darsh\AppData\Local\Temp\ipykernel_15620\55011029.py:22: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  print(datetime.datetime.utcnow())  # Current UTC datetime
C:\Users\darsh\AppData\Local\Temp\ipykernel_15620\55011029.py:38: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  print(datetime.datetime.utcfromtimestamp(0))  # UTC datetime from timestamp


ARRAY  CREATION 

In [13]:
import numpy as np

# Array creation from other Python structures
print("Array creation from other Python structures:")
list1 = [1, 2, 3, 4]
array1 = np.array(list1)
print(array1)

tuple1 = (5, 6, 7, 8)
array2 = np.array(tuple1)
print(array2)

# Intrinsic NumPy array creation functions
print("\nIntrinsic NumPy array creation functions:")
array3 = np.zeros(5)
print(array3)

array4 = np.ones((2, 3))
print(array4)

array5 = np.full((3, 2), 7)
print(array5)

array6 = np.arange(0, 10, 2)
print(array6)

array7 = np.linspace(0, 1, 5)
print(array7)

array8 = np.random.rand(2, 3)
print(array8)

array9 = np.random.randn(3, 3)
print(array9)

array10 = np.random.randint(1, 11, (2, 3))
print(array10)

Array creation from other Python structures:
[1 2 3 4]
[5 6 7 8]

Intrinsic NumPy array creation functions:
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]
 [7 7]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.35078981 0.68940775 0.90295558]
 [0.25480291 0.52154798 0.66657913]]
[[ 0.36795161  0.72654616  1.66970521]
 [ 0.18509334 -1.92100861 -1.57804962]
 [ 2.09868863 -1.15693608 -1.48465534]]
[[5 2 6]
 [2 5 2]]


MATHEMATICAL OPERATIONS  using numpy

In [1]:
import numpy as np

# Arithmetic operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Arithmetic operations:")
print(np.add(x, y))  # Element-wise addition
print(np.subtract(x, y))  # Element-wise subtraction
print(np.multiply(x, y))  # Element-wise multiplication
print(np.divide(x, y))  # Element-wise division
print(np.floor_divide(x, y))  # Element-wise floor division
print(np.mod(x, y))  # Element-wise modulo operation
print(np.power(x, y))  # Element-wise power

# Trigonometric functions
print("\nTrigonometric functions:")
print(np.sin(x))  # Sine of x (in radians)
print(np.cos(x))  # Cosine of x (in radians)
print(np.tan(x))  # Tangent of x (in radians)
print(np.arcsin(x))  # Inverse sine of x (in radians)
print(np.arccos(x))  # Inverse cosine of x (in radians)
print(np.arctan(x))  # Inverse tangent of x (in radians)


# Logarithmic functions
print("\nLogarithmic functions:")
print(np.log(x))  # Natural logarithm of x
print(np.log10(x))  # Base-10 logarithm of x
print(np.log2(x))  # Base-2 logarithm of x

# Exponential functions
print("\nExponential functions:")
print(np.exp(x))  # Exponential function of x
print(np.expm1(x))  # Exponential function of x minus 1
print(np.log1p(x))  # Natural logarithm of 1+x

# Power and root functions
print("\nPower and root functions:")
print(np.power(x, 2))  # Element-wise power
print(np.sqrt(x))  # Square root of x
print(np.cbrt(x))  # Cube root of x

# Ceiling and floor functions
print("\nCeiling and floor functions:")
print(np.ceil(x))  # Ceiling of x (round up to the nearest integer)
print(np.floor(x))  # Floor of x (round down to the nearest integer)

# Rounding functions
print("\nRounding functions:")
print(np.round(x))  # Round x to the nearest integer
print(np.trunc(x))  # Truncate x (remove the decimal part)

# Constants
print("\nConstants:")
print(np.pi)  # Pi
print(np.e)  # Euler's number

Arithmetic operations:
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]
[  1  32 729]

Trigonometric functions:
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
[1.57079633        nan        nan]
[ 0. nan nan]
[0.78539816 1.10714872 1.24904577]

Logarithmic functions:
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[0.        1.        1.5849625]

Exponential functions:
[ 2.71828183  7.3890561  20.08553692]
[ 1.71828183  6.3890561  19.08553692]
[0.69314718 1.09861229 1.38629436]

Power and root functions:
[1 4 9]
[1.         1.41421356 1.73205081]
[1.         1.25992105 1.44224957]

Ceiling and floor functions:
[1. 2. 3.]
[1. 2. 3.]

Rounding functions:
[1 2 3]
[1. 2. 3.]

Constants:
3.141592653589793
2.718281828459045


C:\Users\darsh\AppData\Local\Temp\ipykernel_14284\1376768572.py:21: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))  # Inverse sine of x (in radians)
C:\Users\darsh\AppData\Local\Temp\ipykernel_14284\1376768572.py:22: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(x))  # Inverse cosine of x (in radians)


STATISTICAL  FUNCTION  IN NUMPY

In [18]:
import numpy as np

# Statistical functions

# Mean
data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)
print("Mean:", mean_value)

# Median
median_value = np.median(data)
print("Median:", median_value)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

# Minimum and maximum values
min_value = np.min(data)
max_value = np.max(data)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# Argument of minimum and maximum values
min_index = np.argmin(data)
max_index = np.argmax(data)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)

# Percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)
print("25th percentile:", percentile_25)
print("75th percentile:", percentile_75)

# Quantiles
quantiles = np.quantile(data, [0.25, 0.5, 0.75])
print("Quantiles:", quantiles)


# Correlation coefficient
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
correlation_coeff = np.corrcoef(x, y)[0, 1]
print("Correlation coefficient:", correlation_coeff)

# Covariance
covariance = np.cov(x, y)[0, 1]
print("Covariance:", covariance)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
Minimum value: 1
Maximum value: 5
Index of minimum value: 0
Index of maximum value: 4
25th percentile: 2.0
75th percentile: 4.0
Quantiles: [2. 3. 4.]
Correlation coefficient: 1.0
Covariance: 1.0


LINEAR ALGEBRA

In [20]:
import numpy as np

# Matrix creation
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix operations
print("Matrix operations:")
print(np.add(matrix1, matrix2))  # Matrix addition
print(np.subtract(matrix1, matrix2))  # Matrix subtraction
print(np.dot(matrix1, matrix2))  # Matrix multiplication
print(np.transpose(matrix1))  # Matrix transpose
print(np.linalg.inv(matrix1))  # Matrix inverse

# Eigenvalues and eigenvectors
print("\nEigenvalues and eigenvectors:")
eigenvalues, eigenvectors = np.linalg.eig(matrix1)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

# Determinant and trace
print("\nDeterminant and trace:")
determinant = np.linalg.det(matrix1)
trace = np.trace(matrix1)
print("Determinant:", determinant)
print("Trace:", trace)

# Singular value decomposition (SVD)
print("\nSingular value decomposition (SVD):")
U, sigma, VT = np.linalg.svd(matrix1)
print("U:", U)
print("Sigma:", sigma)
print("VT:", VT)

# QR decomposition
print("\nQR decomposition:")
Q, R = np.linalg.qr(matrix1)
print("Q:", Q)
print("R:", R)

#

# Solving linear equations
print("\nSolving linear equations:")
coefficients = np.array([[2, 1], [5, 3]])
constants = np.array([8, 17])
solution = np.linalg.solve(coefficients, constants)
print("Solution:", solution)

Matrix operations:
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]

Eigenvalues and eigenvectors:
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Determinant and trace:
Determinant: -2.0000000000000004
Trace: 5

Singular value decomposition (SVD):
U: [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Sigma: [5.4649857  0.36596619]
VT: [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]

QR decomposition:
Q: [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R: [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]

Solving linear equations:
Solution: [ 7. -6.]


RANDOM NUMBERS 

In [21]:
import random
import numpy as np

# Generate random integers within a specified range
random_integer = random.randint(1, 10)
print("Random integer:", random_integer)

# Generate random floating-point numbers between 0 and 1
random_float = random.random()
print("Random float:", random_float)

# Generate random integers within a specified range with a step size
random_randrange = random.randrange(1, 10, 2)
print("Random randrange:", random_randrange)

# Generate a random choice from a sequence
sequence = [1, 2, 3, 4, 5]
random_choice = random.choice(sequence)
print("Random choice:", random_choice)

# Shuffle a sequence
random.shuffle(sequence)
print("Shuffled sequence:", sequence)

# Generate random samples from a uniform distribution
random_uniform = np.random.rand(5)
print("Random uniform:", random_uniform)

# Generate random samples from a standard normal distribution
random_normal = np.random.randn(5)
print("Random normal:", random_normal)

# Generate random integers within a specified range
random_integers = np.random.randint(1, 10, size=5)
print("Random integers:", random_integers)

# Seed the random number generator for reproducible results
random.seed(42)
random_number = random.randint(1, 10)
print("Random number with seed:", random_number)

Random integer: 9
Random float: 0.9767395363551664
Random randrange: 5
Random choice: 4
Shuffled sequence: [3, 2, 1, 5, 4]
Random uniform: [0.94977966 0.75160341 0.9161187  0.08135339 0.10239824]
Random normal: [ 0.75306396 -0.25734456 -1.27294598  0.77568328 -0.8415704 ]
Random integers: [9 6 7 4 8]
Random number with seed: 2


NUMPY METHODS  AND FUNCTIONS  IN PYTHON

In [22]:
print("\nFile I/O:")
np.save("array.npy", array1)
loaded_array = np.load("array.npy")
print(loaded_array)

# Other functions
print("\nOther functions:")
print(np.unique(array1))
print(np.intersect1d(array1, array2))
print(np.setdiff1d(array1, array2))
print(np.union1d(array1, array2))


File I/O:
[1 2 3 4]

Other functions:
[1 2 3 4]
[]
[1 2 3 4]
[1 2 3 4 5 6 7 8]


In [23]:
import numpy as np

# Create sample arrays
array1 = np.array([1, 2, 3, 4, 2])
array2 = np.array([3, 4, 5, 6])

# File I/O using NumPy
print("\nFile I/O:")
np.save("array.npy", array1)
loaded_array = np.load("array.npy")
print(loaded_array)  # Output: [1 2 3 4 2]

# Other NumPy functions
print("\nOther functions:")
# Unique values
unique_values = np.unique(array1)
print("Unique values in array1:", unique_values)  # Output: [1 2 3 4]

# Intersection (common elements)
intersection = np.intersect1d(array1, array2)
print("Intersection of array1 and array2:", intersection)  # Output: [3 4]

# Difference (elements in array1 but not array2)
difference = np.setdiff1d(array1, array2)
print("Difference of array1 and array2 (elements in array1 only):", difference)  # Output: [1 2]

# Union (all unique elements from both arrays)
union = np.union1d(array1, array2)
print("Union of array1 and array2:", union)  # Output: [1 2 3 4 5 6]


File I/O:
[1 2 3 4 2]

Other functions:
Unique values in array1: [1 2 3 4]
Intersection of array1 and array2: [3 4]
Difference of array1 and array2 (elements in array1 only): [1 2]
Union of array1 and array2: [1 2 3 4 5 6]


PANDAS
data  creation

PANDAS LIBRARY IN python

In [5]:
import numpy as np
import pandas as p
'''

info():
ddf.info()
it  provides  the summery of  the  data
column names
number of  rows
datatype
number of Non null vlaues
'''
print(type(np))
print(type(p))

<class 'module'>
<class 'module'>


In [16]:
import pandas as p
sd = {
    'Name': ['Alice', 'Bob', 'darshan', 'David', 'darshan', 'Frank', 'Grace', 'Harry', 'Ivy', 'darshan'],
    'Marks': [85, 72, 90, 68, 95, 78, 82, 65, 88, 75]
}
f=p.DataFrame(sd)
#print(f)
k=f.sort_values(by=["Marks"],ascending=False)
#  sorting  the  data   ascending  or  descending  formate

print(k)


      Name  Marks
4  darshan     95
2  darshan     90
8      Ivy     88
0    Alice     85
6    Grace     82
5    Frank     78
9  darshan     75
1      Bob     72
3    David     68
7    Harry     65


FILTERING  DATA

In [18]:
f=f["Name"]=="darshan"
print(f)
print(type(f))

0    False
1    False
2     True
3    False
4     True
5    False
6    False
7    False
8    False
9     True
Name: Name, dtype: bool


In [19]:
import pandas as pd

# Create a dictionary containing student details
student_data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Harry', 'Ivy', 'Jack'],
    'USN': ['123456', '234567', '345678', '456789', '567890', '678901', '789012', '890123', '901234', '012345'],
    'Department': ['CSE', 'ECE', 'EEE', 'ME', 'CE', 'CSE', 'ECE', 'EEE', 'ME', 'CE'],
    'Age': [20, 21, 19, 22, 20, 21, 19, 22, 20, 21],
    'Marks': [85, 72, 90, 68, 95, 78, 82, 65, 88, 75]
}

# Create a Pandas DataFrame from the dictionary
df = pd.DataFrame(student_data)

# Print the DataFrame
print(df)

      Name     USN Department  Age  Marks
0    Alice  123456        CSE   20     85
1      Bob  234567        ECE   21     72
2  Charlie  345678        EEE   19     90
3    David  456789         ME   22     68
4      Eve  567890         CE   20     95
5    Frank  678901        CSE   21     78
6    Grace  789012        ECE   19     82
7    Harry  890123        EEE   22     65
8      Ivy  901234         ME   20     88
9     Jack  012345         CE   21     75


In [22]:
'''  
 Group By:


'''
k=df.groupby(["Department"])["Age"].mean()
print(k)

Department
CE     20.5
CSE    20.5
ECE    20.0
EEE    20.5
ME     21.0
Name: Age, dtype: float64


EXCEPTION HANDLING

In [ ]:
#try:     contains the 
#except:
#handles the specific exception  that  was  raised you  can catch specific exceptions


In [27]:
try:
    n=20
    r=n/0
except Exception as e:
     print("darshan")



else:
     print("hello",r)
finally:
     print("this will  prints  no  matter  what")
     







darshan
this will  prints  no  matter  what


OOPS CONCEPT

In [ ]:
'''
oops  object  oriented  programming  system
class :  define  the  blue print for  object
onject: an instance of a class
attribute :characterstics  of  an object
method; actions an object can perform
inheritance: child  class inherit  from parent  class
polymorphism: objects  have  behav  similarity
encapsulation: hide  the internal  details
abstraction: focus  on the  essential features
'''
class car:
    def __init__(self,color,model):
        self.color=color#  attribute
        #self:  is  the reference to the current instance of the class
        #self.color=color: assign the value of color to the instance attribute
        self.model=model
    def drive(self):# method
        print(f"the {self.color} {self.model}is  driving")

In [ ]:
c1=car("red","benz")
c2=car("red","benz")
c3=car("green","tata")
c1.drive()
c2.drive()
c3.drive()

In [18]:
class dog:
    def __init__(self,name,breed):
        self.name=name
        self.breed=breed
    def bark(self):
        print("wooof")
#creating objects
d1=dog("hello anvi","good moring")
d2=dog("hello deepaaak","morning")
#access    attributes
print(d1.name)
print(d2.breed)
#call  method
d1.bark()
d2.bark()

hello anvi
morning
wooof
wooof


INHERITANCE:

ENCAPSULATION

In [19]:
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
        print("Woof!")

# Create objects
dog1 = Dog("Buddy", "Golden Retriever")
dog2 = Dog("Max", "Labrador")

# Access attributes
print(dog1.name)  # Output: Buddy
print(dog2.breed)  # Output: Labrador

# Call methods
dog1.bark()  # Output: Woof!
dog2.bark()  # Output: Woof!

Buddy
Labrador
Woof!
Woof!


In [17]:
print("darshan")
'''


'''
class person:
    def __init__(self,age,name):#constructor
        self.age=age
        self.name=name
    def getage(self):
        return self.age
p1=person(7,"darshan")#object
p1.name()


darshan


TypeError: 'str' object is not callable

In [4]:
print("darshan")
k={1,2,3,2,1}
l=list(k)




darshan


3

In [13]:
s="darshandarADSGH1232425637ABn".lower().replace("[^a-z]","")
print(s)

darshandaradsgh1232425637abn
